2017-08-11 00:04:53,982={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:14:39,859={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:19:42,196={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:21:02,265={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:23:44,206={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:24:04,842={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:24:49,811={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at BA.IMIS.Common.Data.SQL.ExecuteSPNonQuery(SqlCommand cmd, String DBConn) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\BA.IMIS.Common\Data\SQL.cs:line 47
   at BA.iParts.CompanyRoster.CompanyRosterShared.DeleteFromRoster(String IMIS_ID, String SentByLoginID) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 407
ClientConnectionId:954f68b4-bf98-47d9-9391-4d1d93cbe8cb
Error Number:-2,State:0,Class:11
2017-08-11 00:24:50,119={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:26:14,636={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:27:11,811={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:44:40,516={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:45:57,475={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:47:24,015={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:48:29,790={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:49:30,464={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 00:52:24,436={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 08:43:26,125={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:06:36,373={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:06:57,974={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:07:28,400={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:08:46,498={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:09:53,256={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:10:27,367={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:28:06,012={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:28:26,262={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:29:09,596={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:29:24,123={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:30:21,896={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:32:20,526={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:34:22,740={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 09:34:46,911={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 10:51:20,480={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 10:55:24,300={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:03:41,037={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:04:38,886={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:05:27,956={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:05:55,383={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:06:26,562={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 11:08:33,006={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 13:07:10,361={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 13:07:38,696={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 15:03:07,414={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 15:03:19,820={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 15:03:25,914={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-11 15:36:10,650={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
