2018-07-13 10:01:42,893={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 10:24:48,964={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 10:25:13,722={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 11:01:46,286={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 11:08:19,211={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 11:11:02,161={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 11:24:44,774={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2018-07-13 11:29:36,044={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
