2016-11-24 14:09:02.367 ERROR 6 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 313
2016-11-24 14:09:16.248 ERROR 8 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 313
2016-11-24 14:10:41.187 ERROR 6 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 313
2016-11-24 14:10:45.043 ERROR 7 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 313
2016-11-24 14:10:46.622 ERROR 11 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 313
