2017-03-09 11:25:55.340 ERROR 9 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
2017-03-09 11:35:01.996 ERROR 12 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
2017-03-09 12:02:36.759 ERROR 10 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
2017-03-09 12:19:28.882 ERROR 9 BA.IMIS.Common.Shared - System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
2017-03-09 12:22:24.225 ERROR 10 BA.IMIS.Common.Shared - System.ArgumentException: Column 'ParentOptOutTNB' does not belong to table .
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
2017-03-09 12:29:41.285 ERROR 10 BA.IMIS.Common.Shared - System.ArgumentException: Column 'ParentOptOutTNB' does not belong to table .
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at BA.iParts.CompanyRoster.CompanyRosterShared.GetCompanyRoster(Company company, Boolean IsCoAdmin) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 318
