2017-08-10 11:47:06,146={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 11:48:03,670={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 11:48:39,914={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 14:38:33,369={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 14:40:13,630={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 14:40:14,687={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 14:43:18,143={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 14:47:26,273={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:00:08,868={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:00:56,330={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:02:52,566={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:03:37,369={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:04:41,984={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:12:29,723={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:15:12,312={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:28:42,576={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:29:00,051={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:30:00,939={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:30:12,706={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:32:13,967={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:33:02,785={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at BA.IMIS.Common.Data.SQL.ExecuteSPNonQuery(SqlCommand cmd, String DBConn) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\BA.IMIS.Common\Data\SQL.cs:line 47
   at BA.iParts.CompanyRoster.CompanyRosterShared.DeleteFromRoster(String IMIS_ID, String SentByLoginID) in C:\Users\mike.BA\Documents\Visual Studio 2015\Projects\iMIS Projects\iParts\BACustom\CompanyRoster\BA.iParts.CompanyRoster\Classes\CompanyRoster.cs:line 407
ClientConnectionId:4793bf14-403c-4817-91bc-10d146e72133
Error Number:-2,State:0,Class:11
2017-08-10 15:33:03,029={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:33:04,590={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:36:55,704={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:37:05,782={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:37:53,729={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:39:16,588={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:39:29,347={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:41:27,892={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:42:21,274={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:50:00,038={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:52:14,844={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 15:52:47,132={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 16:26:32,000={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 16:34:11,745={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 23:34:57,869={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 23:45:29,412={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 23:50:58,315={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
2017-08-10 23:57:06,655={ABSOLUTE} [BA.IMIS.Common.Shared] ERROR - System.Exception: Hello World
